"""empty message

Revision ID: 39341c3ee411
Revises: cfab47de9f47
Create Date: 2023-02-12 11:22:55.280298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39341c3ee411'
down_revision = 'cfab47de9f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
